### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by geldarr** [nshttpd/mikrotik-exporter#76] opened 2020-03-17 14:30 UTC
Good afternoon.
After setting exporter up the mikrotik device logs, there are a lot of authorization entries. How do you react to them. Will you disable logs?

**Comment by nshttpd** [comment] 2020-04-08 03:22
I believe this is in the same vein as #65 and a duplicate of that issue.

**Closed by nshttpd** 2020-04-08 03:22 UTC
