### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ozyab09** [nshttpd/mikrotik-exporter#34] opened 2019-02-13 12:15 UTC
Few minutes after starting container  I see an error in logs:

```
{"level":"info","msg":"setting up collector for devices","numDevices":1,"time":"2019-02-13T10:06:02Z"}
{"level":"info","msg":"Listening on :9436","time":"2019-02-13T10:06:02Z"}
panic: runtime error: index out of range

goroutine 88 [running]:
github.com/nshttpd/mikrotik-exporter/collector.parseUptime(0xc420411550, 0x7, 0x829341, 0x6, 0xc4201f2558)
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:108 +0x4a3
github.com/nshttpd/mikrotik-exporter/collector.(*resourceCollector).collectMetricForProperty(0xc42013afc0, 0x829341, 0x6, 0xc42008aec0, 0xc420402680)
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:86 +0x602
github.com/nshttpd/mikrotik-exporter/collector.(*resourceCollector).collectForStat(0xc42013afc0, 0xc42008aec0, 0xc420402680)
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:77 +0x6e
github.com/nshttpd/mikrotik-exporter/collector.(*resourceCollector).collect(0xc42013afc0, 0xc420402680, 0x0, 0x0)
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:56 +0x86
github.com/nshttpd/mikrotik-exporter/collector.(*collector).connectAndCollect(0xc4200cafc0, 0xc420303580, 0xc4200a41e0, 0x0, 0x0)
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:199 +0x369
github.com/nshttpd/mikrotik-exporter/collector.(*collector).collectForDevice(0xc4200cafc0, 0x7ffc5d445c52, 0x8, 0x7ffc5d445c64, 0x9, 0x7ffc5d445c74, 0xa, 0x7ffc5d445c89, 0xa, 0xc4200a41e0)
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:170 +0xc8
github.com/nshttpd/mikrotik-exporter/collector.(*collector).Collect.func1(0xc4200cafc0, 0xc4200a41e0, 0xc4203e28c0, 0x7ffc5d445c52, 0x8, 0x7ffc5d445c64, 0x9, 0x7ffc5d445c74, 0xa, 0x7ffc5d445c89, ...)
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:159 +0x52
created by github.com/nshttpd/mikrotik-exporter/collector.(*collector).Collect
        /go/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:158 +0x131
```
Project starts in Kubernetes cluster.

Application is crashing.

If I use local environment (not kubernetes cluster) then I have no problem with running.

**Comment by nshttpd** [comment] 2019-02-16 22:26
Thanks. I had this happen once and then couldn't reproduce it. Let me spin up minikube in the next couple of days and see if I can reproduce it in there.

**Comment by fresaelens** [comment] 2019-02-20 14:24
Hi,

Maybe the following information is useful for you, as I am getting (kinda) the same error.

I am running the exporter with a separate config file and I get the following error as soon as I have more than 21 devices in the config file:

```
root@buzz:/opt/mikrotik_exporter# ./mikrotik-exporter -config-file mikrotik-exporter.yml
{"level":"info","msg":"setting up collector for devices","numDevices":22,"time":"2019-02-20T15:20:07+01:00"}
{"level":"info","msg":"Listening on :9436","time":"2019-02-20T15:20:07+01:00"}
panic: runtime error: index out of range

goroutine 46 [running]:
github.com/nshttpd/mikrotik-exporter/collector.parseUptime(0xc00029a746, 0xa, 0x84e6d1, 0x6, 0xc000227cf8)
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:108 +0x4ab
github.com/nshttpd/mikrotik-exporter/collector.(*resourceCollector).collectMetricForProperty(0xc000091180, 0x84e6d1, 0x6, 0xc000246a40, 0xc00023acc0)
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:86 +0x5f7
github.com/nshttpd/mikrotik-exporter/collector.(*resourceCollector).collectForStat(0xc000091180, 0xc000246a40, 0xc00023acc0)
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:77 +0x87
github.com/nshttpd/mikrotik-exporter/collector.(*resourceCollector).collect(0xc000091180, 0xc00023acc0, 0x0, 0x0)
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/resource_collector.go:56 +0x86
github.com/nshttpd/mikrotik-exporter/collector.(*collector).connectAndCollect(0xc00009f440, 0xc00009f8c0, 0xc00009cc00, 0x0, 0x0)
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:199 +0x35a
github.com/nshttpd/mikrotik-exporter/collector.(*collector).collectForDevice(0xc00009f440, 0xc0000a9fc0, 0x17, 0xc0000991e0, 0xa, 0xc0000991f8, 0x6, 0xc000099218, 0x8, 0xc00009cc00)
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:170 +0xdb
github.com/nshttpd/mikrotik-exporter/collector.(*collector).Collect.func1(0xc00009f440, 0xc00009cc00, 0xc000099850, 0xc0000a9fc0, 0x17, 0xc0000991e0, 0xa, 0xc0000991f8, 0x6, 0xc000099218, ...)
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:159 +0x66
created by github.com/nshttpd/mikrotik-exporter/collector.(*collector).Collect
	/root/work/src/github.com/nshttpd/mikrotik-exporter/collector/collector.go:158 +0x182
```

As long as I don't have more than 21 devices in my config file the exporter keeps running.

**Comment by nshttpd** [comment] 2019-02-20 16:44
What was the 21st device? I see where the error is in the code and will fix the panic tonight. I'll have it log an error instead to try and figure out if that particular device is returning a strange uptime format or just not returning one at all. Totally blame myself for some lazy coding on that assuming all the devices would report it and report in the same format.

**Comment by nshttpd** [comment] 2019-02-22 03:50
@ozyab09 && @fresaelens ... try version 1.0.6 just built and released. I cleaned up me being lazy and also generated an error on testing it to see what was the real cause. `7w6d9h34m` .. no seconds in the output so the regex was failing. I fixed that too. I'll leave this issue open for a couple of days and if no more errors around this I'll close it after that.

**Closed** 2019-02-26 21:28 UTC
